"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard_page from './dashboard-page.bones.json'
import _thumb_rose_gold from './thumb-rose-gold.bones.json'
import _thumb_botanical from './thumb-botanical.bones.json'
import _thumb_sakura from './thumb-sakura.bones.json'
import _thumb_minimal_modern from './thumb-minimal-modern.bones.json'
import _thumb_lavender_mist from './thumb-lavender-mist.bones.json'
import _thumb_sunset_breeze from './thumb-sunset-breeze.bones.json'
import _thumb_classic_script from './thumb-classic-script.bones.json'
import _thumb_azure_ocean from './thumb-azure-ocean.bones.json'
import _thumb_emerald_forest from './thumb-emerald-forest.bones.json'
import _thumb_cinematic from './thumb-cinematic.bones.json'
import _thumb_vintage_chic from './thumb-vintage-chic.bones.json'
import _thumb_desert_sand from './thumb-desert-sand.bones.json'
import _thumb_amethyst_glance from './thumb-amethyst-glance.bones.json'
import _thumb_arctic_frost from './thumb-arctic-frost.bones.json'
import _thumb_midnight_noir from './thumb-midnight-noir.bones.json'
import _thumb_royal_gold from './thumb-royal-gold.bones.json'
import _thumb_celestial from './thumb-celestial.bones.json'
import _thumb_sacred_ivory from './thumb-sacred-ivory.bones.json'
import _thumb_diamond_regal from './thumb-diamond-regal.bones.json'
import _thumb_enchanted_garden from './thumb-enchanted-garden.bones.json'
import _thumb_opulent_ruby from './thumb-opulent-ruby.bones.json'

registerBones({
  "dashboard-page": _dashboard_page,
  "thumb-rose-gold": _thumb_rose_gold,
  "thumb-botanical": _thumb_botanical,
  "thumb-sakura": _thumb_sakura,
  "thumb-minimal-modern": _thumb_minimal_modern,
  "thumb-lavender-mist": _thumb_lavender_mist,
  "thumb-sunset-breeze": _thumb_sunset_breeze,
  "thumb-classic-script": _thumb_classic_script,
  "thumb-azure-ocean": _thumb_azure_ocean,
  "thumb-emerald-forest": _thumb_emerald_forest,
  "thumb-cinematic": _thumb_cinematic,
  "thumb-vintage-chic": _thumb_vintage_chic,
  "thumb-desert-sand": _thumb_desert_sand,
  "thumb-amethyst-glance": _thumb_amethyst_glance,
  "thumb-arctic-frost": _thumb_arctic_frost,
  "thumb-midnight-noir": _thumb_midnight_noir,
  "thumb-royal-gold": _thumb_royal_gold,
  "thumb-celestial": _thumb_celestial,
  "thumb-sacred-ivory": _thumb_sacred_ivory,
  "thumb-diamond-regal": _thumb_diamond_regal,
  "thumb-enchanted-garden": _thumb_enchanted_garden,
  "thumb-opulent-ruby": _thumb_opulent_ruby,
})
